### ISSUE TITLE
Crash at 80% due to failed attempt to delete S2A_USER_GIP_L2A_[...].xml while in use

### ISSUE THREAD

**Issue by agrapentin** [umwilm/SEN2COR#6]
I am not the only one, see [http://forum.step.esa.int/t/sen2cor-error-could-not-delete-xml/1814](url)

```console
D:\GISDATA\esa>L2A_process --resolution 10 S2A_OPER_PRD_MSIL1C_PDMC_20151228T141534_R116_V20151228T002843_20151228T002843.SAFE

Sentinel-2 Level 2A Prototype Processor (Sen2Cor), 2.0.6, created: 2015.12.02 started ...
check if 20m table exists ...
check if 60m table exists...
Validating metadata file S2A_OPER_MTD_L1C_TL_SGS__20151228T085259_A002687_T54HXD.xml against scheme ...
Metadata file is valid.
L2A_Process: processing with resolution 60 m, elapsed time[s]: 2.107
Progress[%]: 0.14 : L2A_Process: start of pre processing, elapsed time[s]: 0.003
Progress[%]: 0.14 : Validating metadata file S2A_OPER_MTD_SAFL1C_PDMC_20151228T141534_R116_V20151228T002843_20151228T002843.xml against scheme ...
Metadata file is invalid, see logfile for details.
...
Progress[%]: 10.78 : L2A_Tables: stop export, elapsed time[s]: 0.061
Progress[%]: 10.79 : Validating metadata file S2A_USER_MTD_SAFL2A_PDMC_20151228T141534_R116_V20151228T002843_20151228T002843.xml against scheme ...
Metadata file is invalid, see logfile for details.
Validating metadata file S2A_USER_MTD_L2A_TL_SGS__20151228T085259_A002687_T54HXD.xml against scheme ...
Metadata file is invalid, see logfile for details.
...
Progress[%]: 10.83 : Validating metadata file S2A_OPER_MTD_SAFL1C_PDMC_20151228T141534_R116_V20151228T002843_20151228T002843.xml against scheme ...
Metadata file is invalid, see logfile for details.
...
Progress[%]: 79.92 : L2A_Tables: stop export, elapsed time[s]: 0.160
Progress[%]: 79.93 : Validating metadata file S2A_USER_MTD_SAFL2A_PDMC_20151228T141534_R116_V20151228T002843_20151228T002843.xml against scheme ...
Metadata file is invalid, see logfile for details.
Validating metadata file S2A_USER_MTD_L2A_TL_SGS__20151228T085259_A002687_T54HXD.xml against scheme ...
Metadata file is invalid, see logfile for details.
...
Progress[%]: 79.98 : L2A_Process: start of pre processing, elapsed time[s]: 0.004
Progress[%]: 79.98 : Validating metadata file S2A_OPER_MTD_SAFL1C_PDMC_20151228T141534_R116_V20151228T002843_20151228T002843.xml against scheme ...
Metadata file is invalid, see logfile for details.
...
Progress[%]: 79.94 : L2A_Tables: band WVP exported, elapsed time[s]: 19.896
Progress[%]: 81.26 : L2A_Tables: stop export, elapsed time[s]: 0.249
Progress[%]: 81.28 : Traceback (most recent call last):
  File "D:\Miniconda2\Scripts\L2A_Process-script.py", line 9, in <module>
    load_entry_point('sen2cor==2.0.6', 'console_scripts', 'L2A_Process')()
  File "D:\Miniconda2\lib\site-packages\sen2cor-2.0.6-py2.7.egg\sen2cor\L2A_Process.py", line 283, in main
    result = processor.selectAndProcess(tile)
  File "D:\Miniconda2\lib\site-packages\sen2cor-2.0.6-py2.7.egg\sen2cor\L2A_Process.py", line 89, in selectAndProcess
    self._processed10 = self.process()
  File "D:\Miniconda2\lib\site-packages\sen2cor-2.0.6-py2.7.egg\sen2cor\L2A_Process.py", line 152, in process
    if(self.postprocess() == False):
  File "D:\Miniconda2\lib\site-packages\sen2cor-2.0.6-py2.7.egg\sen2cor\L2A_Process.py", line 190, in postprocess
    self.tables.postprocess()
  File "D:\Miniconda2\lib\site-packages\sen2cor-2.0.6-py2.7.egg\sen2cor\L2A_Tables.py", line 1385, in postprocess
    copy_file(self.config.configFn, target)
  File "D:\Miniconda2\lib\distutils\file_util.py", line 156, in copy_file
    _copy_file_contents(src, dst)
  File "D:\Miniconda2\lib\distutils\file_util.py", line 41, in _copy_file_contents
    "could not delete '%s': %s" % (dst, errstr))
distutils.errors.DistutilsFileError: could not delete 'D:\GISDATA\esa/S2A_USER_PRD_MSIL2A_PDMC_20151228T141534_R116_V20151228T002843_20151228T002843.SAFE/GRANULE/S2A_USER_MSI_L2A_TL_SGS__20151228T085259_A002687_T54HXD_N02.01/AUX_DATA\S2A_USER_GIP_L2A_TL_SGS__20151228T085259_A002687_T54HXD.xml': The process cannot access the file because it is being used by another process
```

**Comment by umwilm** [comment]
This error is known and will be fixed with the coming release, which is in preparation and will be released soon.
